### ISSUE TITLE
dmatest failed with memfill.

### ISSUE THREAD

**Issue by hober-yao** [intel/idxd-driver#1]
Hi, dave.

I try to implement memfill function in the idxd driver, but test failed with dmatest.

[  162.954876] dmatest: Added 1 threads using dma0chan0
[  162.955029] dmatest: Started 1 threads using dma0chan0
[  162.955672] dmatest: dma0chan0-copy0: summary 1 tests, 0 failures 2865.32 iops 42979 KB/s (0)
[  177.748420] dmatest: Added 1 threads using dma0chan0
[  177.748585] dmatest: Started 1 threads using dma0chan0
[  177.748792] idxd_dma_submit_memfill called!
[  177.748847] idxd_dma_submit_memfill end!
[  177.749375] dmatest: dma0chan0-set0: dstbuf[0x1856] not copied! Expected de, got 00
[  177.749381] dmatest: dma0chan0-set0: dstbuf[0x1857] not copied! Expected de, got 00
[  177.749382] dmatest: dma0chan0-set0: dstbuf[0x1858] not copied! Expected de, got 00
[  177.749384] dmatest: dma0chan0-set0: dstbuf[0x1859] not copied! Expected de, got 00
[  177.749384] dmatest: dma0chan0-set0: dstbuf[0x185a] not copied! Expected de, got 00
[  177.749385] dmatest: dma0chan0-set0: dstbuf[0x185b] not copied! Expected de, got 00
[  177.749387] dmatest: dma0chan0-set0: dstbuf[0x185c] not copied! Expected de, got 00
[  177.749387] dmatest: dma0chan0-set0: dstbuf[0x185e] not copied! Expected de, got 00
[  177.749388] dmatest: dma0chan0-set0: dstbuf[0x185f] not copied! Expected de, got 00
[  177.749389] dmatest: dma0chan0-set0: dstbuf[0x1860] not copied! Expected de, got 00
[  177.749389] dmatest: dma0chan0-set0: dstbuf[0x1861] not copied! Expected de, got 00
[  177.749391] dmatest: dma0chan0-set0: dstbuf[0x1862] not copied! Expected de, got 00
[  177.749392] dmatest: dma0chan0-set0: dstbuf[0x1863] not copied! Expected de, got 00
[  177.749393] dmatest: dma0chan0-set0: dstbuf[0x1864] not copied! Expected de, got 00
[  177.749395] dmatest: dma0chan0-set0: dstbuf[0x1866] not copied! Expected de, got 00
[  177.749396] dmatest: dma0chan0-set0: dstbuf[0x1867] not copied! Expected de, got 00
[  177.749397] dmatest: dma0chan0-set0: dstbuf[0x1868] not copied! Expected de, got 00
[  177.749398] dmatest: dma0chan0-set0: dstbuf[0x1869] not copied! Expected de, got 00
[  177.749399] dmatest: dma0chan0-set0: dstbuf[0x186a] not copied! Expected de, got 00
[  177.749400] dmatest: dma0chan0-set0: dstbuf[0x186b] not copied! Expected de, got 00
[  177.749400] dmatest: dma0chan0-set0: dstbuf[0x186c] not copied! Expected de, got 00
[  177.749401] dmatest: dma0chan0-set0: dstbuf[0x186e] not copied! Expected de, got 00
[  177.749402] dmatest: dma0chan0-set0: dstbuf[0x186f] not copied! Expected de, got 00
[  177.749402] dmatest: dma0chan0-set0: dstbuf[0x1870] not copied! Expected de, got 00
[  177.749403] dmatest: dma0chan0-set0: dstbuf[0x1871] not copied! Expected de, got 00
[  177.749404] dmatest: dma0chan0-set0: dstbuf[0x1872] not copied! Expected de, got 00
[  177.749404] dmatest: dma0chan0-set0: dstbuf[0x1873] not copied! Expected de, got 00
[  177.749405] dmatest: dma0chan0-set0: dstbuf[0x1874] not copied! Expected de, got 00
[  177.749406] dmatest: dma0chan0-set0: dstbuf[0x1876] not copied! Expected de, got 00
[  177.749407] dmatest: dma0chan0-set0: dstbuf[0x1877] not copied! Expected de, got 00
[  177.749409] dmatest: dma0chan0-set0: dstbuf[0x1878] not copied! Expected de, got 00
[  177.749410] dmatest: dma0chan0-set0: dstbuf[0x1879] not copied! Expected de, got 00
[  177.749432] dmatest: dma0chan0-set0: 7325 errors suppressed
[  177.749435] dmatest: dma0chan0-set0: result #1: 'data error' with src_off=0xc78 dst_off=0x1855 len=0x20d9 (7357)

**Comment by hober-yao** [comment]
code:

         if (idxd->hw.opcap.bits[0] & IDXD_OPCAP_MEMFILL) {
                dma_cap_set(DMA_MEMSET, dma->cap_mask);
                dma->device_prep_dma_memset = idxd_dma_submit_memfill;
        }

static struct dma_async_tx_descriptor *
idxd_dma_submit_memfill(struct dma_chan *c, dma_addr_t dma_dest,
                        int value, size_t len, unsigned long flags)
{
        struct idxd_wq *wq = to_idxd_wq(c);
        u32 desc_flags;
        struct idxd_device *idxd = wq->idxd;
        struct idxd_desc *desc;

        pr_err("%s called!\n", __func__);
        if (wq->state != IDXD_WQ_ENABLED)
                return NULL;

        if (len > idxd->max_xfer_bytes)
                return NULL;

        op_flag_setup(flags, &desc_flags);
        desc = idxd_alloc_desc(wq, IDXD_OP_BLOCK);
        if (IS_ERR(desc))
                return NULL;

        idxd_prep_desc_common(wq, desc->hw, DSA_OPCODE_MEMFILL,
                              value, dma_dest, len, desc->compl_dma,
                              desc_flags);

        desc->txd.flags = flags;
        pr_err("%s end!\n", __func__);
        return &desc->txd;
}

**Comment by hober-yao** [comment]
code
```
        if (idxd->hw.opcap.bits[0] & IDXD_OPCAP_MEMFILL) {
                dma_cap_set(DMA_MEMSET, dma->cap_mask);
                dma->device_prep_dma_memset = idxd_dma_submit_memfill;
        }
        ....
static struct dma_async_tx_descriptor *
idxd_dma_submit_memfill(struct dma_chan *c, dma_addr_t dma_dest,
                        int value, size_t len, unsigned long flags)
{
        struct idxd_wq *wq = to_idxd_wq(c);
        u32 desc_flags;
        struct idxd_device *idxd = wq->idxd;
        struct idxd_desc *desc;

        pr_err("%s called!\n", __func__);
        if (wq->state != IDXD_WQ_ENABLED)
                return NULL;

        if (len > idxd->max_xfer_bytes)
                return NULL;

        op_flag_setup(flags, &desc_flags);
        desc = idxd_alloc_desc(wq, IDXD_OP_BLOCK);
        if (IS_ERR(desc))
                return NULL;

        idxd_prep_desc_common(wq, desc->hw, DSA_OPCODE_MEMFILL,
                              value, dma_dest, len, desc->compl_dma,
                              desc_flags);

        desc->txd.flags = flags;
        pr_err("%s end!\n", __func__);
        return &desc->txd;
}
```

**Comment by davejiang** [comment]
According to the spec, the pattern size is 8 bytes. But the passed in value is an int. I wonder if that causes issues with the resulting written out data. For example. If you pass in 0xabcdabcd, then you would see 0x00000000abcdabcd being written across your data. I don't think that is what you want.

**Comment by hober-yao** [comment]
> According to the spec, the pattern size is 8 bytes. But the passed in value is an int. I wonder if that causes issues with the resulting written out data. For example. If you pass in 0xabcdabcd, then you would see 0x00000000abcdabcd being written across your data. I don't think that is what you want.

**Comment by hober-yao** [comment]
right,  the pattern size should be 8 bytes.
but I modifty the pattern size to 8 bytes, and the problem still exists.  there may be other  errors.
Thank you for reply, i'll debug it myself.

one more question, do you have a plan to support other dsa  operations in idxd?
